#!/bin/csh -f
# interface for plotting E vs. c/a curves
# data is generated with: optimize and "Analyze multiple SCF Files"
#
unalias rm

set tmp  = tmp
set tmp2 = tmp2
set print = eplot.ps
unset type
unset terminal

set file    = `pwd`
set file    = $file:t
set out     = $file.png

unset help

while ($#argv)
  switch ($1)
  case -h:
    set help
    shift; breaksw
  case -t:
    shift
    set type = $1
    shift; breaksw
  case -p:
#    shift
    set terminal = png
    shift; breaksw
  case -f:
    shift; set file = $1
    shift; breaksw
  default:
    shift; breaksw
  endsw
end
if ($?help) goto help

if !(-e $file.analysis) goto error


if !($?type) then
    echo 'type   "coa"  for c/a or' 
    echo '       "vol"  for volume curve '
    set type=$<
endif

if ( $type == 'vol' ) then


set ene=`grep :ENE $file.analysis | cut -f2 -d=`
set vol=`grep :VOL $file.analysis | cut -f2 -d=`
if (-e $file.vol) rm $file.vol
set i = 0
loop:
 echo $vol[$i] $ene[$i] >>$file.vol
 @ i ++
if ( $i <= $#ene ) goto loop

echo -e "0" | x eosfit -f $file
    echo '       "display Murnaghan or Birch-Murnaghan fit: [M/B]"  '
    # set fit=$<
    set fit = M
echo "You may want to print $file.outputeos"
cat $file.outputeos
echo " Murnaghan-data are in $file.eosfit"
echo " Birch-Murnaghan-data are in $file.eosfitb"
  switch ($fit)
  case [B,b]:
     set murna=`grep V0, $file.outputeos | grep -v \* | tail -1`
     set plotfile=$file.eosfitb
    breaksw
  default:
     set murna=`grep V0, $file.outputeos | grep -v \* | tail -2 | head -1`
     set plotfile=$file.eosfit
    breaksw
  endsw

set fonts_file = "$HOME/.fonts/ARIAL.TTF"
set title_file = `echo $file | sed 's/_/\\\\_/g'`
echo "MURNA = $murna[2]"
set alat3 = `echo $murna[2] | awk '{print $1^(1/3)}'`
set alat3 = `printf "%.6f" $alat3`
set alat  = `echo "scale=8; $alat3 / 3" | bc`
set alat  = `printf "%.6f" $alat`
echo "ALAT  = $alat"
echo "ALAT3 = $alat3"
rm -fv $file.optimized_*
echo "ALAT = $alat"   >  $file.optimized_$alat3
echo "ALAT3 = $alat3" >> $file.optimized_$alat3
echo "ALAT = $alat"   >> $file.outputeos
echo "ALAT3 = $alat3" >> $file.outputeos

cat <<EOF >$tmp
set terminal png enhanced font "$fonts_file" 20 size 1280,960
set output "$out"
#set data style linespoints
set format y "%.4f"
set title "$title_file"
plot "$file.vol" title "Murnaghan: $murna[1]" w p,"$plotfile" title "alat=$alat; $murna[2-]" w l 
EOF
gnuplot $tmp
endif
else

# here we do coa's

#grep $type $file.analysis |sed "1d"| sed "s/.*$type//" |cut -c1-6,56- | tr "_" " " |sort -n >$tmp2

grep $type $file.analysis | grep -v "Analysis generated" | grep -v ":VOL " |\
 sed "s/.*$type//" | tr ":a-z" " " | awk '{print $1 " " $NF}'|\
 cut -c1-6,8-  | tr "_" " " |sort -n >$tmp2

echo ' ' >$tmp
if ($?terminal) then
cat <<EOF >$tmp
set terminal png
set output '$file.c_over_a.png'
EOF
endif

cat <<EOF >>$tmp
set xlabel "deviation from exp. c/a ratio (%)"
set ylabel "Energy [Ry]"
set format y "%.4f"
f(x)=a1+a2*x+a3*x**2+a4*x**3+a5*x**4
fit f(x) '$tmp2' via '.fitparam'
plot "$tmp2" title "data" w p , f(x) title "polyfit_4order"
#plot "$tmp2" title "$file"
EOF
if (! $?terminal) echo pause -1 >>$tmp

cat <<EOF >.fitparam
a1=1
a2=1
a3=1
a4=1
a5=1
EOF

gnuplot $tmp

if ($?terminal) then
    set out=eplot.ps
    set hardcopy=y
else
    echo -n "Do you want a hardcopy? (y/N)"
    set hardcopy = ($<)
    if ($hardcopy == y) then
	echo -n "Specify a filename (default is $print)"
	set out = ($<)
	echo "Printing hardcopy"
	if ($out == "") set out = "$print"
    endif
endif
#echo "press RETURN to continue" $hardcopy 
if ($hardcopy == y) then
	cat <<EOF >$tmp
set terminal postscript
set output "$out"
#set data style linespoints
set format y "%.4f"
f(x)=a1+a2*x+a3*x**2+a4*x**3+a5*x**4
fit f(x) '$tmp2' via '.fitparam'
plot "$tmp2" title "data" w p , f(x) title "polyfit_4order"
#plot "$tmp2" title "$file"
EOF
gnuplot $tmp >& /dev/null
if ($?terminal) echo $file.c_over_a.png generated
echo $out generated
endif



endif
#rm $tmp $tmp2

exit  0

error:
echo ">>>"
echo ">>> ERROR: $file.analysis not found\!"
echo ">>> ERROR:"
echo '>>> ERROR: You should "Anaylze multiple SCF Files" first'
echo ">>>"
#exit(1)

help:

cat <<EOF
EPLOT is a plotting interface to plot E vs. Vol or c/a curves.
Once you have several scf calculations at different volumes (usually generated 
with "optimize.job") you can generate the required "$file.analysis" using:
grepline :ENE "*.scf" 1 >  $file.analysis
grepline :VOL "*.scf" 1 >> $file.analysis
Generates plots in X-window (default), png (-p) and ps format.

eplot [-t vol/coa] [-p] [-f FILEHEAD]

EOF
