#!/bin/bash

dir=$PWD/$(hostname)
if [ ! -d "$dir" ]; then
    mkdir $dir
else
    echo "  Dir $dir exists. Exiting..."
    exit 1
fi

for((i=1; i<=120; i++)); do
    i_tmp=$(echo "00000$i" | rev | cut -c 1-3 | rev)
    echo $i_tmp
    ps -ef > $dir/$(hostname).ps."$i_tmp"
    sleep 1
done

exit 0

